# Livy configuration
livy.server.host = 0.0.0.0
livy.server.port = 8998
livy.spark.master = ${SPARK_MASTER:-spark://spark-master:7077}
livy.spark.deploy-mode = client
livy.server.session.timeout = 1h
livy.server.session.state-retain.sec = 600
livy.repl.enable-hive-context = false
livy.file.local-dir-whitelist = /tmp
